version: '3.3'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_PASSWORD: '1234'
      # Password for root access
      MYSQL_ROOT_PASSWORD: '1234'
      MYSQL_DATABASE: 'bieber'
      MYSQL_ROOT_HOST: '%'
    ports:
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
# Names our volume
volumes:
  my-db: